### ISSUE TITLE
docker container keeps restarting

### ISSUE THREAD

**Issue by mmagician** [smartcontractkit/chainlink-polkadot#36]
When running `./setup.sh`, the containers are all started, but the ones for chainlink nodes keep restarting.
To check the logs I run `docker-compose up`, where I see two possible culprits:

```
chainlink-node1_1           | error starting app: websocket: bad handshake (HTTP status 403 Forbidden)
substrate-chainlink_chainlink-node1_1 exited with code 1
```
&

```
external-initiator-node3_1  | 2020-09-12T16:20:13Z [ERROR] ic_accesskey flag or EI_IC_ACCESSKEY env must be set client/client.go:108             stacktrace=github.com/smartcontractkit/chainlink/core/logger.Error
```

Any clues on how to proceed?

Thanks!

**Comment by stefanobaldo** [comment]
I'm having the same issue. It seems that the error happens when it tries to access wss://ropsten.infura.io/ws.
Any clues?

**Comment by LaurentTrk** [comment]
Hi @mmagician , @stefanobaldo 

Infura needs a project key in the URL. 
I don't know if it's a new requirement, nor if it has been working without a project key, nor if we need another step to do to make the `setup` to work correctly.

As a workaround, you have to [register](https://infura.io/register) on Infura and [create a new project](https://infura.io/dashboard/ethereum), then use the correct URL for the Ropsten network (see the value in the settings of your project, be sure to select the correct network in the list).
The value has to be set in the `substrate-chainlink/chainlink.env` file :
``` 
ETH_URL=wss://ropsten.infura.io/ws/v3/####YOUR_PROJECT_KEY####
``` 

Hope it help...

**Comment by krebernisak** [comment]
Hi guys! Thanks for reporting this.

We had a similar issue with our [external-initiator integration tests](https://github.com/smartcontractkit/external-initiator/issues/68).

This got broken in Chainlink node `0.8.13` release.

We are working on a fix, but until then you can fix the version to 0.8.12 in the Dockerfile to avoid the issue and make the integration tests run.

**Comment by se3000** [comment]
Should be fixed by https://github.com/smartcontractkit/chainlink/pull/3382, which should be included in a 0.8.16 release later today.

**Comment by mmagician** [comment]
@LaurentTrk [That](https://github.com/smartcontractkit/chainlink-polkadot/issues/36#issuecomment-694701872) worked, thanks.
Looking forward to the new release!

**Comment by krebernisak** [comment]
Closing this issue as 0.8.16 is now released.

**Comment by mmagician** [comment]
@krebernisak It hasn't helped, the container just keeps restarting & this is what I'm seeing in the logs:
```
2020-09-22T21:05:18Z [DEBUG] Initializing API credentials from /run/secrets/apicredentials cmd/client.go:434
2020-09-22T21:05:19Z [INFO]  API exposed for user notreal@fakeemail.ch          cmd/local_client.go:95
2020-09-22T21:05:19Z [DEBUG] eth.Client#Dial(...)                               eth/client.go:110
error starting app: websocket: bad handshake (HTTP status 403 Forbidden)
```

If I include the URL from Infura as @LaurentTrk pointed out in the workaround above, I am able to start the chainlink node just fine.
I can verify that I'm running `smartcontract/chainlink:0.8.16`.
