### ISSUE TITLE
Creating new jobs with external initiator throws a 401

### ISSUE THREAD

**Issue by mmagician** [smartcontractkit/chainlink-polkadot#38]
Running the individual steps of the `setup` scripts, I supposedly get a successful run, but no job is ever created (and `jobids.txt` contains `null` 3 times).

When I try to create the job from UI with the following parameters - (see attached [file](https://github.com/smartcontractkit/chainlink-polkadot/files/5250712/jobspec.txt) I get:

`
notify 'test-ei' (http://substrate-chainlink_external-initiator-node1_1:8080/jobs) received bad response '401 Unauthorized'
`

Where the job parameters are from `add-jobspec.sh`, filling in the account from `setup` script.

I'm not sure where I'd provide the auth credentials. Could you offer any help please? I guess that since this tutorial has been released, the API of both the chainlink node as well as external initiator have changed significantly.

Many thanks!!! I'm almost there 👍  Once I get it all working, I'll make a PR which brings this repo up to date with latest substrate & chainlink versions.

**Comment by LaurentTrk** [comment]
> Running the individual steps of the setup scripts, I supposedly get a successful run, but no job is ever created (and jobids.txt contains null 3 times).

May I ask you which os and docker version you are using ?  

I experienced the same issue on Linux, and got the setup working, see https://discord.com/channels/592041321326182401/752523925317222429/756543202520989716.

**Comment by mmagician** [comment]
I'm on newest docker on Mac OS.
I'm not 100% sure it's the same issue, since I am actually reaching out to the external initiator.

**Comment by mmagician** [comment]
@LaurentTrk any idea then? I think we misunderstood each other here.
I'm still on a 401 error, but the issue you're seeing is different from mine. If I weren't able to connect to it, I would see it plainly as a message. A 401 to me means that I can connect, but somehow I'm missing credentials.

**Comment by LaurentTrk** [comment]
Yes, credentials are build during setup (see `add-ei.sh`)
I suppose you have launch the setup multiple times ? 
I could suggest you to done it one more time, with a full cleanup:
```
cd substrate-chainlink
docker-compose down -v
rm -Rf external_initiator* jobids.txt tmp
./setup
```

**Comment by mmagician** [comment]
@LaurentTrk Thanks that did the job! I'm currently running into another issue with metadata v11 not supported (https://github.com/centrifuge/go-substrate-rpc-client/issues/93) - though I see the type already present [here](https://github.com/centrifuge/go-substrate-rpc-client/blob/master/types/metadataV11.go). Is it because it's not complete yet? As at the moment I'm not able to create jobs, perhaps there is a workaround?

Thanks a lot for your continued support

**Comment by LaurentTrk** [comment]
Same issue here, but I manage to create jobs.
I ran into this issue when trying to update polkadot-chainlink to last chainlink version.
I keep you update with my findings :)

**Comment by LaurentTrk** [comment]
@mmagician I fixed the issues for v11 metadata and some missing events (see https://github.com/LaurentTrk/go-substrate-rpc-client/tree/fix/chainlink).
Need some tests, and then I will publish new docker version for Initiator and Substrate EA.

**Comment by mmagician** [comment]
@LaurentTrk Awesome! 
Have a look at the PR I opened there, maybe you could integrate that one as well?
https://github.com/centrifuge/go-substrate-rpc-client/pull/96/

**Comment by mmagician** [comment]
Using `laurenttrk/external-initiator:2.0.0-alpha.6.4` & `laurenttrk/substrate-adapter:2.0.0-alpha.6.4` solved it!
