### ISSUE TITLE
FATAL: Unable to initialize the API: createType(RequestIdentifier):: Cannot construct unknown type RequestIdentifier

### ISSUE THREAD

**Issue by menduong** [smartcontractkit/chainlink-polkadot#73]

**Comment by mattsse** [comment]
I'm guessing you're using the polkadot.js UI?

You need to register the chainlink pallet types the chainlink types directly in the polkadot UI -> Settings -> Developer:
https://github.com/smartcontractkit/chainlink-polkadot/blob/master/substrate-node-example/front-end/src/config/types.json

**Comment by menduong** [comment]
Thanks you. I already fixed it
